export const topicMap: Record<string, string[]> = {
  Bus: ["bus routes", "public transport", "bus timetable", "local buses"],
  Crime: [
    "police cuts",
    "crime",
    "stabbing",
    "knife crime",
    "anti-social behaviour",
    "gangs",
    "police response time",
    "vandalism",
  ],
  "Cost of living": [
    "poverty",
    "price increases",
    "cost of living",
    "inflation",
    "electricity price increase",
    "energy price increase",
    "petrol price increase",
    "mortgage rates",
    "food price increases",
    "fuel price increase",
  ],
  Cuts: ["public service cuts", "hospital cuts", "school cuts", "council cuts"],
  Economy: [
    "inflation",
    "mortgage rates",
    "house prices",
    "wages",
    "GDP growth",
  ],
  Education: [
    "school funding cuts",
    "class sizes",
    "teachers shortages",
    "pupil premium",
  ],
  Election: [
    "election",
    "prime minister",
    "Sunak",
    "Starmer",
    "ballot box",
    "polling station",
    "candidates",
    "UK general election",
    "voter registration",
  ],
  Energy: ["energy price cap", "Ofgem", "energy tariffs", "fossil fuels"],
  Jobs: [
    "jobs",
    "employment",
    "unemployment",
    "vacancies",
    "labour market",
    "Universal Credit",
  ],
  "Levelling up": [
    "levelling up",
    "freeports",
    "Network North",
    "Investment Zones",
    "regional inequality",
    "region",
    "town",
  ],
  NHS: [
    "NHS",
    "hospital waiting list",
    "doctor",
    "GP",
    "appointments",
    "hospital",
    "healthcare",
    "nurse",
    "operation delays",
    "NHS waiting times",
    "surgery backlog",
    "A&E queues",
  ],
  Potholes: ["potholes", "street repair", "road maintenance"],
  Rail: [
    "trains",
    "train delays",
    "franchise rail",
    "commuters",
    "journey times",
    "cancellations UK trains",
    "delays train",
  ],
  Sewage: [
    "water company",
    "sewage discharges",
    "privatised water",
    "beaches sewage",
  ],
  Transport: ["passengers", "tube", "TFL", "petrol prices", "public transport"],
};
